server:
    port: 9998
spring:
    application:
        name: proxy-service
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
#eureka:
#    client:
#        service-url:
#            defaultZone: https://sp-euraka-service.herokuapp.com/eureka/
#hystrix:
#    command:
#        default:
#            execution:
#                timeout:
#                    enabled: true
#                isolation:
#                    thread:
#                        timeoutInMilliseconds: 30000
#ribbon:
#    ReadTimeout: 10000
#    ConnectTimeout: 10000
