server:
    port: 8888
spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/marielevha/service-suppliers.git
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/